name: Publish Nuxt Frontend

on:
  push:
    branches:
      - main

jobs:
  update_ssh_linode:
    name: Telling Linode to update the Nuxt frontend
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: actions/setup-node@v3
        with:
          node-version: 18
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash portfoliopush.sh